FROM httpd:2.4

RUN apt-get update && apt-get install -y git

WORKDIR /usr/src/app

RUN rm -rf /usr/local/apache2/htdocs/*

RUN git clone https://github.com/denilsonbonatti/linux-site-dio.git /usr/local/apache2/htdocs/




